container:
  image: debian:testing-slim

test_task:
  env:
    - CODECOV_TOKEN: ENCRYPTED[ad1fc181f1c3415471271f2d2b5a00ece0d2f14e6147f3ea028ad594109db25c54baf54e6d27cb97e73dd151e1df4ece]
    - matrix:
      - CC: gcc
      - CC: clang
  setup_script:
    - apt-get update
    - |
      apt-get install -y \
        curl \
        scons \
        bison \
        flex \
        dejagnu \
        lcov \
        gcc \
        clang
  test_script: scons coverage=yes check distcheck coverage.info
  allow_failures: $CC == 'clang'
  coverage_script: bash <(curl -s https://codecov.io/bash) -f coverage.info
