language: c
sudo: false
before_install:
 - gem install coveralls-lcov
addons: {apt: {packages: &native_deps [scons, bison, flex, dejagnu, lcov]}}
after_success:
 - coveralls-lcov coverage.info
before_script:
 - $COMPILER --version
 - scons --version
 - flex --version
 - bison --version
 - runtest --version
script:
 - CC=$COMPILER scons coverage=$COVERAGE check distcheck
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [gcc-4.9, *native_deps]
      env: COMPILER=gcc-4.9 COVERAGE=yes
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [gcc-5, *native_deps]
      env: COMPILER=gcc-5 COVERAGE=yes
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [gcc-6, *native_deps]
      env: COMPILER=gcc-6 COVERAGE=yes
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [gcc-7, *native_deps]
      env: COMPILER=gcc-7 COVERAGE=yes
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.6
          packages: [clang-3.6, *native_deps]
      env: COMPILER=clang-3.6 COVERAGE=no
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.7
          packages: [clang-3.7, *native_deps]
      env: COMPILER=clang-3.7 COVERAGE=no
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages: [clang-4.0, *native_deps]
      env: COMPILER=clang-4.0 COVERAGE=no
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-3.8
          packages: [clang-5.0, *native_deps]
      env: COMPILER=clang-5.0 COVERAGE=no
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages: [clang-3.8, *native_deps]
      env: COMPILER=clang-3.8 COVERAGE=no
  allow_failures:
    - env: COMPILER=gcc-7 COVERAGE=no
    - env: COMPILER=clang-3.7 COVERAGE=no
    - env: COMPILER=clang-3.8 COVERAGE=no
    - env: COMPILER=clang-4.0 COVERAGE=no
    - env: COMPILER=clang-5.0 COVERAGE=no
