language: c
sudo: false
addons:
  apt:
    packages:
    - bison
    - flex
    - dejagnu
compiler:
 - clang
 - gcc
before_install:
 - pip install --user cpp-coveralls
  - if [ "$CC" == "gcc" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CC" == "clang" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq
install:
  - if [ "$CC" == "gcc" ]; then sudo apt-get install -qq gcc-4.8; sudo update-alternatives --install /usr/bin/gcc /usr/bin/gcc-4.8; fi
  - if [ "$CC" == "clang" ]; then sudo apt-get install --allow-unauthenticated -qq clang-3.4; fi
after_success:
 - coveralls --exclude t --exclude testsuite --gcov-options '\-lp'
script:
  - scons -v
  - scons -k gcov=yes debug=yes
  - runtest --all --debug -v -v
