language: c
sudo: true
dist: trusty
before_install:
 - pip install --user cpp-coveralls
addons: {apt: {packages: &native_deps [scons, bison, flex, dejagnu]}}
after_success:
 - coveralls --exclude input/filtergen/t --exclude input/iptables-save/t --exclude testsuite --gcov-options '\-lp'
before_script:
 - $COMPILER --version
 - scons --version
 - flex --version
 - bison --version
 - runtest --version
script:
 - CC=$COMPILER scons -k gcov=yes debug=yes
 - runtest --all --debug -v -v
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [gcc-4.9, *native_deps]
      env: COMPILER=gcc-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [gcc-5, *native_deps]
      env: COMPILER=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages: [clang-3.6, *native_deps]
      env: COMPILER=clang-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages: [clang-3.7, *native_deps]
      env: COMPILER=clang-3.7
  allow_failures:
    - compiler: clang
