language: c
sudo: true
dist: trusty
before_install:
 - pip install --user cpp-coveralls
addons:
  apt:
    packages:
    - scons
    - bison
    - flex
    - dejagnu
    - gcov
after_success:
 - coveralls --exclude t --exclude testsuite --gcov-options '\-lp'
before_script:
 - scons --version
 - flex --version
 - bison --version
 - gcov --version
 - runtest --version
script:
 - scons -k gcov=yes debug=yes
 - runtest --all --debug -v -v
