language: c
sudo: true
dist: trusty
before_install:
 - pip install --user cpp-coveralls
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    packages:
    # install toolchains
    - clang-3.6
    - scons
    - bison
    - flex
    - dejagnu
    - gcov
after_success:
 - coveralls --exclude input/filtergen/t --exclude input/iptables-save/t --exclude testsuite --gcov-options '\-lp'
before_script:
 - scons --version
 - flex --version
 - bison --version
 - gcov --version
 - runtest --version
script:
 - scons -k gcov=yes debug=yes
 - runtest --all --debug -v -v
compiler:
  - gcc
  - clang
matrix:
  allow_failures:
    - compiler: clang
