language: c
sudo: true
dist: trusty
before_install:
 - gem install coveralls-lcov
addons: {apt: {packages: &native_deps [scons, bison, flex, dejagnu, lcov]}}
after_success:
 - lcov --capture --directory . --output-file coverage.info --remove input/filtergen/t --remove input/iptables-save/t --remove .sconf_temp --exclude testsuite
 - coveralls-lcov coverage.info
before_script:
 - $COMPILER --version
 - scons --version
 - flex --version
 - bison --version
 - runtest --version
script:
 - CC=$COMPILER scons -k gcov=yes debug=yes check distcheck
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [gcc-4.9, *native_deps]
      env: COMPILER=gcc-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: [gcc-5, *native_deps]
      env: COMPILER=gcc-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.6
          packages: [clang-3.6, *native_deps]
      env: COMPILER=clang-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.7
          packages: [clang-3.7, *native_deps]
      env: COMPILER=clang-3.7
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-3.8
          packages: [clang-3.8, *native_deps]
      env: COMPILER=clang-3.8
  allow_failures:
    - env: COMPILER=clang-3.7
    - env: COMPILER=clang-3.8
