language: c
sudo: false
addons:
  apt:
    packages:
    - bison
    - flex
compiler:
 - clang
 - gcc
after_failure: cat t/test-suite.log
before_install:
 - pip install --user cpp-coveralls
after_success:
 - coveralls --exclude t --gcov-options '\-lp'
script: scons -k gcov=yes
