language: c
sudo: false
addons:
  apt:
    packages:
    - bison
    - flex
    - dejagnu
compiler:
 - clang
 - gcc
before_install:
 - pip install --user cpp-coveralls
after_success:
 - coveralls --exclude t --exclude testsuite --gcov-options '\-lp'
script:
  - scons -v
  - scons -k gcov=yes debug=yes
  - runtest --all --debug -v -v
